<?php

use AD7six\Dsn\Dsn;

class DATABASE_CONFIG {

/**
 * DO NOT EDIT THIS FILE
 *
 * Define connections using environment variables
 *
 * @return void
 */
	public function __construct() {
		$configs = array(
			'default' => Dsn::parse(env('DATABASE_URL'))->toArray(),
			'test' => Dsn::parse(env('DATABASE_TEST_URL'))->toArray(),
		);

		foreach ($configs as $connection => $config) {
			$this->$connection = $config;
		}
	}

}
