<?php
class DATABASE_CONFIG {

/**
 * DO NOT EDIT THIS FILE
 *
 * Define connections using environment variables
 *
 * @return void
 */
	public function __construct() {
		App::uses('Env', 'Lib');
		$configs = Env::parseDb();
		foreach ($configs as $connection => $config) {
			$this->$connection = $config;
		}
	}

}
