<?php

use AD7six\Dsn\Dsn;

class DATABASE_CONFIG {

/**
 * DO NOT EDIT THIS FILE
 *
 * Define connections using environment variables
 *
 * @return void
 */
	public function __construct() {
		$keyMap = [
			'scheme' => 'datasource', // insufficient
			'user' => 'login',
			'pass' => 'password',
		];
		$configs = array(
			'default' => Dsn::parse(env('DATABASE_URL'), $keyMap)->toArray(),
			'test' => Dsn::parse(env('DATABASE_TEST_URL'), $keyMap)->toArray(),
		);

		foreach ($configs as $connection => $config) {
			$this->$connection = $config;
		}
	}

}
