<?php

use AD7six\Dsn\Dsn;

class EmailConfig {

/**
 * DO NOT EDIT THIS FILE
 *
 * Define connections using environment variables
 *
 * @return void
 */
	public function __construct() {
		$keyMap = [
			'scheme' => 'transport',
			'user' => 'username',
			'pass' => 'password',
		];
		$configs = array(
			'default' => Dsn::parse(env('EMAIL_URL'), $keyMap)->toArray(),
			'smtp' => Dsn::parse(env('EMAIL_SMTP_URL'), $keyMap)->toArray(),
			'fast' => Dsn::parse(env('EMAIL_FAST_URL'), $keyMap)->toArray()
		);

		foreach ($configs as $connection => $config) {
			$this->$connection = $config;
		}
	}

}
