<?php
class EmailConfig {

/**
 * DO NOT EDIT THIS FILE
 *
 * Define connections using environment variables
 *
 * @return void
 */
	public function __construct() {
		App::uses('Env', 'Lib');
		$configs = array(
			'default' => Env::parseEmailUrl(env('EMAIL_URL')),
			'smtp' => Env::parseEmailUrl(env('EMAIL_SMTP_URL')),
			'fast' => Env::parseEmailUrl(env('EMAIL_FAST_URL')),
		);

		foreach ($configs as $connection => $config) {
			$this->$connection = $config;
		}
	}

}
